/*
 * This program source code file is part of KiCad, a free EDA CAD application.
 *
 * Copyright (C) 2024 KiCad Developers, see AUTHORS.txt for contributors.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

syntax = "proto3";

package kiapi.schematic.commands;

import "common/types/base_types.proto";

// Requests a list of nets in the schematic
message GetNets
{
  kiapi.common.types.DocumentSpecifier document = 1;
}

message NetInfo
{
  string name = 1;
  int32  code = 2;
}

message GetNetsResponse
{
  repeated NetInfo nets = 1;
}

// Requests the sheet hierarchy
message GetSheetHierarchy
{
  kiapi.common.types.DocumentSpecifier document = 1;
}

message SheetInfo
{
  string                    path     = 1;
  string                    name     = 2;
  string                    filename = 3;
  string                    page     = 4;
  kiapi.common.types.KIID   id       = 5;
}

message GetSheetHierarchyResponse
{
  repeated SheetInfo sheets = 1;
}
